import IconIndex from "../node_modules/@ikkowy/icons/icons.json";

import IwyIcon from "./components/IwyIcon.vue";

import IwyIconArrowBarDownRegularSvg from "@ikkowy/icons/regular/SVG/arrow-bar-down.svg?component";
import IwyIconArrowBarLeftRegularSvg from "@ikkowy/icons/regular/SVG/arrow-bar-left.svg?component";
import IwyIconArrowBarRightRegularSvg from "@ikkowy/icons/regular/SVG/arrow-bar-right.svg?component";
import IwyIconArrowBarUpRegularSvg from "@ikkowy/icons/regular/SVG/arrow-bar-up.svg?component";
import IwyIconArrowDownRegularSvg from "@ikkowy/icons/regular/SVG/arrow-down.svg?component";
import IwyIconArrowLeftRegularSvg from "@ikkowy/icons/regular/SVG/arrow-left.svg?component";
import IwyIconArrowRightRegularSvg from "@ikkowy/icons/regular/SVG/arrow-right.svg?component";
import IwyIconArrowUpRegularSvg from "@ikkowy/icons/regular/SVG/arrow-up.svg?component";
import IwyIconAsteriskRegularSvg from "@ikkowy/icons/regular/SVG/asterisk.svg?component";
import IwyIconAsteriskCircleRegularSvg from "@ikkowy/icons/regular/SVG/asterisk-circle.svg?component";
import IwyIconAsteriskCircleSolidSvg from "@ikkowy/icons/solid/SVG/asterisk-circle.svg?component";
import IwyIconAsteriskSquareRegularSvg from "@ikkowy/icons/regular/SVG/asterisk-square.svg?component";
import IwyIconAsteriskSquareSolidSvg from "@ikkowy/icons/solid/SVG/asterisk-square.svg?component";
import IwyIconBellRegularSvg from "@ikkowy/icons/regular/SVG/bell.svg?component";
import IwyIconBellSolidSvg from "@ikkowy/icons/solid/SVG/bell.svg?component";
import IwyIconBellOffRegularSvg from "@ikkowy/icons/regular/SVG/bell-off.svg?component";
import IwyIconBellOffSolidSvg from "@ikkowy/icons/solid/SVG/bell-off.svg?component";
import IwyIconBellRingRegularSvg from "@ikkowy/icons/regular/SVG/bell-ring.svg?component";
import IwyIconBellRingSolidSvg from "@ikkowy/icons/solid/SVG/bell-ring.svg?component";
import IwyIconBookRegularSvg from "@ikkowy/icons/regular/SVG/book.svg?component";
import IwyIconBookSolidSvg from "@ikkowy/icons/solid/SVG/book.svg?component";
import IwyIconBookmarkRegularSvg from "@ikkowy/icons/regular/SVG/bookmark.svg?component";
import IwyIconBookmarkSolidSvg from "@ikkowy/icons/solid/SVG/bookmark.svg?component";
import IwyIconBulletCircleRegularSvg from "@ikkowy/icons/regular/SVG/bullet-circle.svg?component";
import IwyIconBulletCircleSolidSvg from "@ikkowy/icons/solid/SVG/bullet-circle.svg?component";
import IwyIconBulletSquareRegularSvg from "@ikkowy/icons/regular/SVG/bullet-square.svg?component";
import IwyIconBulletSquareSolidSvg from "@ikkowy/icons/solid/SVG/bullet-square.svg?component";
import IwyIconCheckRegularSvg from "@ikkowy/icons/regular/SVG/check.svg?component";
import IwyIconCheckCircleRegularSvg from "@ikkowy/icons/regular/SVG/check-circle.svg?component";
import IwyIconCheckCircleSolidSvg from "@ikkowy/icons/solid/SVG/check-circle.svg?component";
import IwyIconCheckSquareRegularSvg from "@ikkowy/icons/regular/SVG/check-square.svg?component";
import IwyIconCheckSquareSolidSvg from "@ikkowy/icons/solid/SVG/check-square.svg?component";
import IwyIconChevronDownRegularSvg from "@ikkowy/icons/regular/SVG/chevron-down.svg?component";
import IwyIconChevronLeftRegularSvg from "@ikkowy/icons/regular/SVG/chevron-left.svg?component";
import IwyIconChevronRightRegularSvg from "@ikkowy/icons/regular/SVG/chevron-right.svg?component";
import IwyIconChevronUpRegularSvg from "@ikkowy/icons/regular/SVG/chevron-up.svg?component";
import IwyIconCircleRegularSvg from "@ikkowy/icons/regular/SVG/circle.svg?component";
import IwyIconCircleSolidSvg from "@ikkowy/icons/solid/SVG/circle.svg?component";
import IwyIconClockRegularSvg from "@ikkowy/icons/regular/SVG/clock.svg?component";
import IwyIconClockSolidSvg from "@ikkowy/icons/solid/SVG/clock.svg?component";
import IwyIconCrossRegularSvg from "@ikkowy/icons/regular/SVG/cross.svg?component";
import IwyIconCrossCircleRegularSvg from "@ikkowy/icons/regular/SVG/cross-circle.svg?component";
import IwyIconCrossCircleSolidSvg from "@ikkowy/icons/solid/SVG/cross-circle.svg?component";
import IwyIconCrossSquareRegularSvg from "@ikkowy/icons/regular/SVG/cross-square.svg?component";
import IwyIconCrossSquareSolidSvg from "@ikkowy/icons/solid/SVG/cross-square.svg?component";
import IwyIconDarkRegularSvg from "@ikkowy/icons/regular/SVG/dark.svg?component";
import IwyIconDarkSolidSvg from "@ikkowy/icons/solid/SVG/dark.svg?component";
import IwyIconDotsHorizontalRegularSvg from "@ikkowy/icons/regular/SVG/dots-horizontal.svg?component";
import IwyIconDotsVerticalRegularSvg from "@ikkowy/icons/regular/SVG/dots-vertical.svg?component";
import IwyIconDoubleChevronDownRegularSvg from "@ikkowy/icons/regular/SVG/double-chevron-down.svg?component";
import IwyIconDoubleChevronLeftRegularSvg from "@ikkowy/icons/regular/SVG/double-chevron-left.svg?component";
import IwyIconDoubleChevronRightRegularSvg from "@ikkowy/icons/regular/SVG/double-chevron-right.svg?component";
import IwyIconDoubleChevronUpRegularSvg from "@ikkowy/icons/regular/SVG/double-chevron-up.svg?component";
import IwyIconDoubleSpinRegularSvg from "@ikkowy/icons/regular/SVG/double-spin.svg?component";
import IwyIconDoubleWedgeDownRegularSvg from "@ikkowy/icons/regular/SVG/double-wedge-down.svg?component";
import IwyIconDoubleWedgeLeftRegularSvg from "@ikkowy/icons/regular/SVG/double-wedge-left.svg?component";
import IwyIconDoubleWedgeRightRegularSvg from "@ikkowy/icons/regular/SVG/double-wedge-right.svg?component";
import IwyIconDoubleWedgeUpRegularSvg from "@ikkowy/icons/regular/SVG/double-wedge-up.svg?component";
import IwyIconErlenmeyerFlaskRegularSvg from "@ikkowy/icons/regular/SVG/erlenmeyer-flask.svg?component";
import IwyIconExitRegularSvg from "@ikkowy/icons/regular/SVG/exit.svg?component";
import IwyIconExitSolidSvg from "@ikkowy/icons/solid/SVG/exit.svg?component";
import IwyIconExportRegularSvg from "@ikkowy/icons/regular/SVG/export.svg?component";
import IwyIconExportSolidSvg from "@ikkowy/icons/solid/SVG/export.svg?component";
import IwyIconEyeRegularSvg from "@ikkowy/icons/regular/SVG/eye.svg?component";
import IwyIconEyeSolidSvg from "@ikkowy/icons/solid/SVG/eye.svg?component";
import IwyIconEyeOffRegularSvg from "@ikkowy/icons/regular/SVG/eye-off.svg?component";
import IwyIconEyeOffSolidSvg from "@ikkowy/icons/solid/SVG/eye-off.svg?component";
import IwyIconFilterRegularSvg from "@ikkowy/icons/regular/SVG/filter.svg?component";
import IwyIconFilterSolidSvg from "@ikkowy/icons/solid/SVG/filter.svg?component";
import IwyIconFilterOffRegularSvg from "@ikkowy/icons/regular/SVG/filter-off.svg?component";
import IwyIconFilterOffSolidSvg from "@ikkowy/icons/solid/SVG/filter-off.svg?component";
import IwyIconGearRegularSvg from "@ikkowy/icons/regular/SVG/gear.svg?component";
import IwyIconGearSolidSvg from "@ikkowy/icons/solid/SVG/gear.svg?component";
import IwyIconGroupRegularSvg from "@ikkowy/icons/regular/SVG/group.svg?component";
import IwyIconGroupSolidSvg from "@ikkowy/icons/solid/SVG/group.svg?component";
import IwyIconHelpRegularSvg from "@ikkowy/icons/regular/SVG/help.svg?component";
import IwyIconHelpSolidSvg from "@ikkowy/icons/solid/SVG/help.svg?component";
import IwyIconImportRegularSvg from "@ikkowy/icons/regular/SVG/import.svg?component";
import IwyIconImportSolidSvg from "@ikkowy/icons/solid/SVG/import.svg?component";
import IwyIconInfoRegularSvg from "@ikkowy/icons/regular/SVG/info.svg?component";
import IwyIconInfoSolidSvg from "@ikkowy/icons/solid/SVG/info.svg?component";
import IwyIconKeyRegularSvg from "@ikkowy/icons/regular/SVG/key.svg?component";
import IwyIconKeySolidSvg from "@ikkowy/icons/solid/SVG/key.svg?component";
import IwyIconLightRegularSvg from "@ikkowy/icons/regular/SVG/light.svg?component";
import IwyIconLightSolidSvg from "@ikkowy/icons/solid/SVG/light.svg?component";
import IwyIconMailRegularSvg from "@ikkowy/icons/regular/SVG/mail.svg?component";
import IwyIconMailSolidSvg from "@ikkowy/icons/solid/SVG/mail.svg?component";
import IwyIconMenuRegularSvg from "@ikkowy/icons/regular/SVG/menu.svg?component";
import IwyIconMenuOpenRegularSvg from "@ikkowy/icons/regular/SVG/menu-open.svg?component";
import IwyIconMessageRegularSvg from "@ikkowy/icons/regular/SVG/message.svg?component";
import IwyIconMessageSolidSvg from "@ikkowy/icons/solid/SVG/message.svg?component";
import IwyIconMessageOffRegularSvg from "@ikkowy/icons/regular/SVG/message-off.svg?component";
import IwyIconMessageOffSolidSvg from "@ikkowy/icons/solid/SVG/message-off.svg?component";
import IwyIconMinusRegularSvg from "@ikkowy/icons/regular/SVG/minus.svg?component";
import IwyIconMinusCircleRegularSvg from "@ikkowy/icons/regular/SVG/minus-circle.svg?component";
import IwyIconMinusCircleSolidSvg from "@ikkowy/icons/solid/SVG/minus-circle.svg?component";
import IwyIconMinusSquareRegularSvg from "@ikkowy/icons/regular/SVG/minus-square.svg?component";
import IwyIconMinusSquareSolidSvg from "@ikkowy/icons/solid/SVG/minus-square.svg?component";
import IwyIconPencilRegularSvg from "@ikkowy/icons/regular/SVG/pencil.svg?component";
import IwyIconPhoneRegularSvg from "@ikkowy/icons/regular/SVG/phone.svg?component";
import IwyIconPhoneSolidSvg from "@ikkowy/icons/solid/SVG/phone.svg?component";
import IwyIconPhoneReceiverRegularSvg from "@ikkowy/icons/regular/SVG/phone-receiver.svg?component";
import IwyIconPhoneReceiverCrossRegularSvg from "@ikkowy/icons/regular/SVG/phone-receiver-cross.svg?component";
import IwyIconPhoneReceiverInRegularSvg from "@ikkowy/icons/regular/SVG/phone-receiver-in.svg?component";
import IwyIconPhoneReceiverOffRegularSvg from "@ikkowy/icons/regular/SVG/phone-receiver-off.svg?component";
import IwyIconPhoneReceiverOutRegularSvg from "@ikkowy/icons/regular/SVG/phone-receiver-out.svg?component";
import IwyIconPinRegularSvg from "@ikkowy/icons/regular/SVG/pin.svg?component";
import IwyIconPinSolidSvg from "@ikkowy/icons/solid/SVG/pin.svg?component";
import IwyIconPinOffRegularSvg from "@ikkowy/icons/regular/SVG/pin-off.svg?component";
import IwyIconPinOffSolidSvg from "@ikkowy/icons/solid/SVG/pin-off.svg?component";
import IwyIconPlusRegularSvg from "@ikkowy/icons/regular/SVG/plus.svg?component";
import IwyIconPlusCircleRegularSvg from "@ikkowy/icons/regular/SVG/plus-circle.svg?component";
import IwyIconPlusCircleSolidSvg from "@ikkowy/icons/solid/SVG/plus-circle.svg?component";
import IwyIconPlusSquareRegularSvg from "@ikkowy/icons/regular/SVG/plus-square.svg?component";
import IwyIconPlusSquareSolidSvg from "@ikkowy/icons/solid/SVG/plus-square.svg?component";
import IwyIconSearchRegularSvg from "@ikkowy/icons/regular/SVG/search.svg?component";
import IwyIconServerRegularSvg from "@ikkowy/icons/regular/SVG/server.svg?component";
import IwyIconServerSolidSvg from "@ikkowy/icons/solid/SVG/server.svg?component";
import IwyIconSpinRegularSvg from "@ikkowy/icons/regular/SVG/spin.svg?component";
import IwyIconSquareRegularSvg from "@ikkowy/icons/regular/SVG/square.svg?component";
import IwyIconSquareSolidSvg from "@ikkowy/icons/solid/SVG/square.svg?component";
import IwyIconStarRegularSvg from "@ikkowy/icons/regular/SVG/star.svg?component";
import IwyIconStarSolidSvg from "@ikkowy/icons/solid/SVG/star.svg?component";
import IwyIconStopwatchRegularSvg from "@ikkowy/icons/regular/SVG/stopwatch.svg?component";
import IwyIconStopwatchSolidSvg from "@ikkowy/icons/solid/SVG/stopwatch.svg?component";
import IwyIconTaskRegularSvg from "@ikkowy/icons/regular/SVG/task.svg?component";
import IwyIconTaskSolidSvg from "@ikkowy/icons/solid/SVG/task.svg?component";
import IwyIconTestTubeRegularSvg from "@ikkowy/icons/regular/SVG/test-tube.svg?component";
import IwyIconTrashcanRegularSvg from "@ikkowy/icons/regular/SVG/trashcan.svg?component";
import IwyIconTrashcanSolidSvg from "@ikkowy/icons/solid/SVG/trashcan.svg?component";
import IwyIconTrashcanCrossRegularSvg from "@ikkowy/icons/regular/SVG/trashcan-cross.svg?component";
import IwyIconTrashcanCrossSolidSvg from "@ikkowy/icons/solid/SVG/trashcan-cross.svg?component";
import IwyIconTriangleDownRegularSvg from "@ikkowy/icons/regular/SVG/triangle-down.svg?component";
import IwyIconTriangleDownSolidSvg from "@ikkowy/icons/solid/SVG/triangle-down.svg?component";
import IwyIconTriangleLeftRegularSvg from "@ikkowy/icons/regular/SVG/triangle-left.svg?component";
import IwyIconTriangleLeftSolidSvg from "@ikkowy/icons/solid/SVG/triangle-left.svg?component";
import IwyIconTriangleRightRegularSvg from "@ikkowy/icons/regular/SVG/triangle-right.svg?component";
import IwyIconTriangleRightSolidSvg from "@ikkowy/icons/solid/SVG/triangle-right.svg?component";
import IwyIconTriangleUpRegularSvg from "@ikkowy/icons/regular/SVG/triangle-up.svg?component";
import IwyIconTriangleUpSolidSvg from "@ikkowy/icons/solid/SVG/triangle-up.svg?component";
import IwyIconUnknownRegularSvg from "@ikkowy/icons/regular/SVG/unknown.svg?component";
import IwyIconUnknownSolidSvg from "@ikkowy/icons/solid/SVG/unknown.svg?component";
import IwyIconUserCircleRegularSvg from "@ikkowy/icons/regular/SVG/user-circle.svg?component";
import IwyIconUserCircleSolidSvg from "@ikkowy/icons/solid/SVG/user-circle.svg?component";
import IwyIconUserRegularSvg from "@ikkowy/icons/regular/SVG/user.svg?component";
import IwyIconUserSolidSvg from "@ikkowy/icons/solid/SVG/user.svg?component";
import IwyIconVaultRegularSvg from "@ikkowy/icons/regular/SVG/vault.svg?component";
import IwyIconVaultSolidSvg from "@ikkowy/icons/solid/SVG/vault.svg?component";
import IwyIconWarningRegularSvg from "@ikkowy/icons/regular/SVG/warning.svg?component";
import IwyIconWarningSolidSvg from "@ikkowy/icons/solid/SVG/warning.svg?component";
import IwyIconWedgeBarDownRegularSvg from "@ikkowy/icons/regular/SVG/wedge-bar-down.svg?component";
import IwyIconWedgeBarLeftRegularSvg from "@ikkowy/icons/regular/SVG/wedge-bar-left.svg?component";
import IwyIconWedgeBarRightRegularSvg from "@ikkowy/icons/regular/SVG/wedge-bar-right.svg?component";
import IwyIconWedgeBarUpRegularSvg from "@ikkowy/icons/regular/SVG/wedge-bar-up.svg?component";
import IwyIconWedgeDownRegularSvg from "@ikkowy/icons/regular/SVG/wedge-down.svg?component";
import IwyIconWedgeLeftRegularSvg from "@ikkowy/icons/regular/SVG/wedge-left.svg?component";
import IwyIconWedgeRightRegularSvg from "@ikkowy/icons/regular/SVG/wedge-right.svg?component";
import IwyIconWedgeUpRegularSvg from "@ikkowy/icons/regular/SVG/wedge-up.svg?component";
import IwyIconZigzagRegularSvg from "@ikkowy/icons/regular/SVG/zigzag.svg?component";
import IwyIconZigzagSolidSvg from "@ikkowy/icons/solid/SVG/zigzag.svg?component";

export default {
  install: (app, options) => {
    app.component("IwyIcon", IwyIcon);

    app.component("IwyIconArrowBarDownRegularSvg", IwyIconArrowBarDownRegularSvg);
    app.component("IwyIconArrowBarLeftRegularSvg", IwyIconArrowBarLeftRegularSvg);
    app.component("IwyIconArrowBarRightRegularSvg", IwyIconArrowBarRightRegularSvg);
    app.component("IwyIconArrowBarUpRegularSvg", IwyIconArrowBarUpRegularSvg);
    app.component("IwyIconArrowDownRegularSvg", IwyIconArrowDownRegularSvg);
    app.component("IwyIconArrowLeftRegularSvg", IwyIconArrowLeftRegularSvg);
    app.component("IwyIconArrowRightRegularSvg", IwyIconArrowRightRegularSvg);
    app.component("IwyIconArrowUpRegularSvg", IwyIconArrowUpRegularSvg);
    app.component("IwyIconAsteriskRegularSvg", IwyIconAsteriskRegularSvg);
    app.component("IwyIconAsteriskCircleRegularSvg", IwyIconAsteriskCircleRegularSvg);
    app.component("IwyIconAsteriskCircleSolidSvg", IwyIconAsteriskCircleSolidSvg);
    app.component("IwyIconAsteriskSquareRegularSvg", IwyIconAsteriskSquareRegularSvg);
    app.component("IwyIconAsteriskSquareSolidSvg", IwyIconAsteriskSquareSolidSvg);
    app.component("IwyIconBellRegularSvg", IwyIconBellRegularSvg);
    app.component("IwyIconBellSolidSvg", IwyIconBellSolidSvg);
    app.component("IwyIconBellOffRegularSvg", IwyIconBellOffRegularSvg);
    app.component("IwyIconBellOffSolidSvg", IwyIconBellOffSolidSvg);
    app.component("IwyIconBellRingRegularSvg", IwyIconBellRingRegularSvg);
    app.component("IwyIconBellRingSolidSvg", IwyIconBellRingSolidSvg);
    app.component("IwyIconBookRegularSvg", IwyIconBookRegularSvg);
    app.component("IwyIconBookSolidSvg", IwyIconBookSolidSvg);
    app.component("IwyIconBookmarkRegularSvg", IwyIconBookmarkRegularSvg);
    app.component("IwyIconBookmarkSolidSvg", IwyIconBookmarkSolidSvg);
    app.component("IwyIconBulletCircleRegularSvg", IwyIconBulletCircleRegularSvg);
    app.component("IwyIconBulletCircleSolidSvg", IwyIconBulletCircleSolidSvg);
    app.component("IwyIconBulletSquareRegularSvg", IwyIconBulletSquareRegularSvg);
    app.component("IwyIconBulletSquareSolidSvg", IwyIconBulletSquareSolidSvg);
    app.component("IwyIconCheckRegularSvg", IwyIconCheckRegularSvg);
    app.component("IwyIconCheckCircleRegularSvg", IwyIconCheckCircleRegularSvg);
    app.component("IwyIconCheckCircleSolidSvg", IwyIconCheckCircleSolidSvg);
    app.component("IwyIconCheckSquareRegularSvg", IwyIconCheckSquareRegularSvg);
    app.component("IwyIconCheckSquareSolidSvg", IwyIconCheckSquareSolidSvg);
    app.component("IwyIconChevronDownRegularSvg", IwyIconChevronDownRegularSvg);
    app.component("IwyIconChevronLeftRegularSvg", IwyIconChevronLeftRegularSvg);
    app.component("IwyIconChevronRightRegularSvg", IwyIconChevronRightRegularSvg);
    app.component("IwyIconChevronUpRegularSvg", IwyIconChevronUpRegularSvg);
    app.component("IwyIconCircleRegularSvg", IwyIconCircleRegularSvg);
    app.component("IwyIconCircleSolidSvg", IwyIconCircleSolidSvg);
    app.component("IwyIconClockRegularSvg", IwyIconClockRegularSvg);
    app.component("IwyIconClockSolidSvg", IwyIconClockSolidSvg);
    app.component("IwyIconCrossRegularSvg", IwyIconCrossRegularSvg);
    app.component("IwyIconCrossCircleRegularSvg", IwyIconCrossCircleRegularSvg);
    app.component("IwyIconCrossCircleSolidSvg", IwyIconCrossCircleSolidSvg);
    app.component("IwyIconCrossSquareRegularSvg", IwyIconCrossSquareRegularSvg);
    app.component("IwyIconCrossSquareSolidSvg", IwyIconCrossSquareSolidSvg);
    app.component("IwyIconDarkRegularSvg", IwyIconDarkRegularSvg);
    app.component("IwyIconDarkSolidSvg", IwyIconDarkSolidSvg);
    app.component("IwyIconDotsHorizontalRegularSvg", IwyIconDotsHorizontalRegularSvg);
    app.component("IwyIconDotsVerticalRegularSvg", IwyIconDotsVerticalRegularSvg);
    app.component("IwyIconDoubleChevronDownRegularSvg", IwyIconDoubleChevronDownRegularSvg);
    app.component("IwyIconDoubleChevronLeftRegularSvg", IwyIconDoubleChevronLeftRegularSvg);
    app.component("IwyIconDoubleChevronRightRegularSvg", IwyIconDoubleChevronRightRegularSvg);
    app.component("IwyIconDoubleChevronUpRegularSvg", IwyIconDoubleChevronUpRegularSvg);
    app.component("IwyIconDoubleSpinRegularSvg", IwyIconDoubleSpinRegularSvg);
    app.component("IwyIconDoubleWedgeDownRegularSvg", IwyIconDoubleWedgeDownRegularSvg);
    app.component("IwyIconDoubleWedgeLeftRegularSvg", IwyIconDoubleWedgeLeftRegularSvg);
    app.component("IwyIconDoubleWedgeRightRegularSvg", IwyIconDoubleWedgeRightRegularSvg);
    app.component("IwyIconDoubleWedgeUpRegularSvg", IwyIconDoubleWedgeUpRegularSvg);
    app.component("IwyIconErlenmeyerFlaskRegularSvg", IwyIconErlenmeyerFlaskRegularSvg);
    app.component("IwyIconExitRegularSvg", IwyIconExitRegularSvg);
    app.component("IwyIconExitSolidSvg", IwyIconExitSolidSvg);
    app.component("IwyIconExportRegularSvg", IwyIconExportRegularSvg);
    app.component("IwyIconExportSolidSvg", IwyIconExportSolidSvg);
    app.component("IwyIconEyeRegularSvg", IwyIconEyeRegularSvg);
    app.component("IwyIconEyeSolidSvg", IwyIconEyeSolidSvg);
    app.component("IwyIconEyeOffRegularSvg", IwyIconEyeOffRegularSvg);
    app.component("IwyIconEyeOffSolidSvg", IwyIconEyeOffSolidSvg);
    app.component("IwyIconFilterRegularSvg", IwyIconFilterRegularSvg);
    app.component("IwyIconFilterSolidSvg", IwyIconFilterSolidSvg);
    app.component("IwyIconFilterOffRegularSvg", IwyIconFilterOffRegularSvg);
    app.component("IwyIconFilterOffSolidSvg", IwyIconFilterOffSolidSvg);
    app.component("IwyIconGearRegularSvg", IwyIconGearRegularSvg);
    app.component("IwyIconGearSolidSvg", IwyIconGearSolidSvg);
    app.component("IwyIconGroupRegularSvg", IwyIconGroupRegularSvg);
    app.component("IwyIconGroupSolidSvg", IwyIconGroupSolidSvg);
    app.component("IwyIconHelpRegularSvg", IwyIconHelpRegularSvg);
    app.component("IwyIconHelpSolidSvg", IwyIconHelpSolidSvg);
    app.component("IwyIconImportRegularSvg", IwyIconImportRegularSvg);
    app.component("IwyIconImportSolidSvg", IwyIconImportSolidSvg);
    app.component("IwyIconInfoRegularSvg", IwyIconInfoRegularSvg);
    app.component("IwyIconInfoSolidSvg", IwyIconInfoSolidSvg);
    app.component("IwyIconKeyRegularSvg", IwyIconKeyRegularSvg);
    app.component("IwyIconKeySolidSvg", IwyIconKeySolidSvg);
    app.component("IwyIconLightRegularSvg", IwyIconLightRegularSvg);
    app.component("IwyIconLightSolidSvg", IwyIconLightSolidSvg);
    app.component("IwyIconMailRegularSvg", IwyIconMailRegularSvg);
    app.component("IwyIconMailSolidSvg", IwyIconMailSolidSvg);
    app.component("IwyIconMenuRegularSvg", IwyIconMenuRegularSvg);
    app.component("IwyIconMenuOpenRegularSvg", IwyIconMenuOpenRegularSvg);
    app.component("IwyIconMessageRegularSvg", IwyIconMessageRegularSvg);
    app.component("IwyIconMessageSolidSvg", IwyIconMessageSolidSvg);
    app.component("IwyIconMessageOffRegularSvg", IwyIconMessageOffRegularSvg);
    app.component("IwyIconMessageOffSolidSvg", IwyIconMessageOffSolidSvg);
    app.component("IwyIconMinusRegularSvg", IwyIconMinusRegularSvg);
    app.component("IwyIconMinusCircleRegularSvg", IwyIconMinusCircleRegularSvg);
    app.component("IwyIconMinusCircleSolidSvg", IwyIconMinusCircleSolidSvg);
    app.component("IwyIconMinusSquareRegularSvg", IwyIconMinusSquareRegularSvg);
    app.component("IwyIconMinusSquareSolidSvg", IwyIconMinusSquareSolidSvg);
    app.component("IwyIconPencilRegularSvg", IwyIconPencilRegularSvg);
    app.component("IwyIconPhoneRegularSvg", IwyIconPhoneRegularSvg);
    app.component("IwyIconPhoneSolidSvg", IwyIconPhoneSolidSvg);
    app.component("IwyIconPhoneReceiverRegularSvg", IwyIconPhoneReceiverRegularSvg);
    app.component("IwyIconPhoneReceiverCrossRegularSvg", IwyIconPhoneReceiverCrossRegularSvg);
    app.component("IwyIconPhoneReceiverInRegularSvg", IwyIconPhoneReceiverInRegularSvg);
    app.component("IwyIconPhoneReceiverOffRegularSvg", IwyIconPhoneReceiverOffRegularSvg);
    app.component("IwyIconPhoneReceiverOutRegularSvg", IwyIconPhoneReceiverOutRegularSvg);
    app.component("IwyIconPinRegularSvg", IwyIconPinRegularSvg);
    app.component("IwyIconPinSolidSvg", IwyIconPinSolidSvg);
    app.component("IwyIconPinOffRegularSvg", IwyIconPinOffRegularSvg);
    app.component("IwyIconPinOffSolidSvg", IwyIconPinOffSolidSvg);
    app.component("IwyIconPlusRegularSvg", IwyIconPlusRegularSvg);
    app.component("IwyIconPlusCircleRegularSvg", IwyIconPlusCircleRegularSvg);
    app.component("IwyIconPlusCircleSolidSvg", IwyIconPlusCircleSolidSvg);
    app.component("IwyIconPlusSquareRegularSvg", IwyIconPlusSquareRegularSvg);
    app.component("IwyIconPlusSquareSolidSvg", IwyIconPlusSquareSolidSvg);
    app.component("IwyIconSearchRegularSvg", IwyIconSearchRegularSvg);
    app.component("IwyIconServerRegularSvg", IwyIconServerRegularSvg);
    app.component("IwyIconServerSolidSvg", IwyIconServerSolidSvg);
    app.component("IwyIconSpinRegularSvg", IwyIconSpinRegularSvg);
    app.component("IwyIconSquareRegularSvg", IwyIconSquareRegularSvg);
    app.component("IwyIconSquareSolidSvg", IwyIconSquareSolidSvg);
    app.component("IwyIconStarRegularSvg", IwyIconStarRegularSvg);
    app.component("IwyIconStarSolidSvg", IwyIconStarSolidSvg);
    app.component("IwyIconStopwatchRegularSvg", IwyIconStopwatchRegularSvg);
    app.component("IwyIconStopwatchSolidSvg", IwyIconStopwatchSolidSvg);
    app.component("IwyIconTaskRegularSvg", IwyIconTaskRegularSvg);
    app.component("IwyIconTaskSolidSvg", IwyIconTaskSolidSvg);
    app.component("IwyIconTestTubeRegularSvg", IwyIconTestTubeRegularSvg);
    app.component("IwyIconTrashcanRegularSvg", IwyIconTrashcanRegularSvg);
    app.component("IwyIconTrashcanSolidSvg", IwyIconTrashcanSolidSvg);
    app.component("IwyIconTrashcanCrossRegularSvg", IwyIconTrashcanCrossRegularSvg);
    app.component("IwyIconTrashcanCrossSolidSvg", IwyIconTrashcanCrossSolidSvg);
    app.component("IwyIconTriangleDownRegularSvg", IwyIconTriangleDownRegularSvg);
    app.component("IwyIconTriangleDownSolidSvg", IwyIconTriangleDownSolidSvg);
    app.component("IwyIconTriangleLeftRegularSvg", IwyIconTriangleLeftRegularSvg);
    app.component("IwyIconTriangleLeftSolidSvg", IwyIconTriangleLeftSolidSvg);
    app.component("IwyIconTriangleRightRegularSvg", IwyIconTriangleRightRegularSvg);
    app.component("IwyIconTriangleRightSolidSvg", IwyIconTriangleRightSolidSvg);
    app.component("IwyIconTriangleUpRegularSvg", IwyIconTriangleUpRegularSvg);
    app.component("IwyIconTriangleUpSolidSvg", IwyIconTriangleUpSolidSvg);
    app.component("IwyIconUnknownRegularSvg", IwyIconUnknownRegularSvg);
    app.component("IwyIconUnknownSolidSvg", IwyIconUnknownSolidSvg);
    app.component("IwyIconUserCircleRegularSvg", IwyIconUserCircleRegularSvg);
    app.component("IwyIconUserCircleSolidSvg", IwyIconUserCircleSolidSvg);
    app.component("IwyIconUserRegularSvg", IwyIconUserRegularSvg);
    app.component("IwyIconUserSolidSvg", IwyIconUserSolidSvg);
    app.component("IwyIconVaultRegularSvg", IwyIconVaultRegularSvg);
    app.component("IwyIconVaultSolidSvg", IwyIconVaultSolidSvg);
    app.component("IwyIconWarningRegularSvg", IwyIconWarningRegularSvg);
    app.component("IwyIconWarningSolidSvg", IwyIconWarningSolidSvg);
    app.component("IwyIconWedgeBarDownRegularSvg", IwyIconWedgeBarDownRegularSvg);
    app.component("IwyIconWedgeBarLeftRegularSvg", IwyIconWedgeBarLeftRegularSvg);
    app.component("IwyIconWedgeBarRightRegularSvg", IwyIconWedgeBarRightRegularSvg);
    app.component("IwyIconWedgeBarUpRegularSvg", IwyIconWedgeBarUpRegularSvg);
    app.component("IwyIconWedgeDownRegularSvg", IwyIconWedgeDownRegularSvg);
    app.component("IwyIconWedgeLeftRegularSvg", IwyIconWedgeLeftRegularSvg);
    app.component("IwyIconWedgeRightRegularSvg", IwyIconWedgeRightRegularSvg);
    app.component("IwyIconWedgeUpRegularSvg", IwyIconWedgeUpRegularSvg);
    app.component("IwyIconZigzagRegularSvg", IwyIconZigzagRegularSvg);
    app.component("IwyIconZigzagSolidSvg", IwyIconZigzagSolidSvg);
  },
};

export { IconIndex };
