import IconIndex from "../node_modules/@ikkowy/icons/icons.json";

import IwyIcon from "./components/IwyIcon.vue";

import IwyIconArrowDownRegularSvg from "@ikkowy/icons/regular/SVG/arrow-down.svg?component";
import IwyIconArrowLeftRegularSvg from "@ikkowy/icons/regular/SVG/arrow-left.svg?component";
import IwyIconArrowRightRegularSvg from "@ikkowy/icons/regular/SVG/arrow-right.svg?component";
import IwyIconArrowUpRegularSvg from "@ikkowy/icons/regular/SVG/arrow-up.svg?component";
import IwyIconBackRegularSvg from "@ikkowy/icons/regular/SVG/back.svg?component";
import IwyIconBellRegularSvg from "@ikkowy/icons/regular/SVG/bell.svg?component";
import IwyIconBellSolidSvg from "@ikkowy/icons/solid/SVG/bell.svg?component";
import IwyIconBellOffRegularSvg from "@ikkowy/icons/regular/SVG/bell-off.svg?component";
import IwyIconBellOffSolidSvg from "@ikkowy/icons/solid/SVG/bell-off.svg?component";
import IwyIconBellRingRegularSvg from "@ikkowy/icons/regular/SVG/bell-ring.svg?component";
import IwyIconBellRingSolidSvg from "@ikkowy/icons/solid/SVG/bell-ring.svg?component";
import IwyIconBookRegularSvg from "@ikkowy/icons/regular/SVG/book.svg?component";
import IwyIconBookSolidSvg from "@ikkowy/icons/solid/SVG/book.svg?component";
import IwyIconBulletCircleRegularSvg from "@ikkowy/icons/regular/SVG/bullet-circle.svg?component";
import IwyIconBulletCircleSolidSvg from "@ikkowy/icons/solid/SVG/bullet-circle.svg?component";
import IwyIconBulletSquareRegularSvg from "@ikkowy/icons/regular/SVG/bullet-square.svg?component";
import IwyIconBulletSquareSolidSvg from "@ikkowy/icons/solid/SVG/bullet-square.svg?component";
import IwyIconCheckRegularSvg from "@ikkowy/icons/regular/SVG/check.svg?component";
import IwyIconCheckCircleRegularSvg from "@ikkowy/icons/regular/SVG/check-circle.svg?component";
import IwyIconCheckCircleSolidSvg from "@ikkowy/icons/solid/SVG/check-circle.svg?component";
import IwyIconCheckSquareRegularSvg from "@ikkowy/icons/regular/SVG/check-square.svg?component";
import IwyIconCheckSquareSolidSvg from "@ikkowy/icons/solid/SVG/check-square.svg?component";
import IwyIconCircleRegularSvg from "@ikkowy/icons/regular/SVG/circle.svg?component";
import IwyIconCircleSolidSvg from "@ikkowy/icons/solid/SVG/circle.svg?component";
import IwyIconClockRegularSvg from "@ikkowy/icons/regular/SVG/clock.svg?component";
import IwyIconClockSolidSvg from "@ikkowy/icons/solid/SVG/clock.svg?component";
import IwyIconCrossRegularSvg from "@ikkowy/icons/regular/SVG/cross.svg?component";
import IwyIconCrossCircleRegularSvg from "@ikkowy/icons/regular/SVG/cross-circle.svg?component";
import IwyIconCrossCircleSolidSvg from "@ikkowy/icons/solid/SVG/cross-circle.svg?component";
import IwyIconCrossSquareRegularSvg from "@ikkowy/icons/regular/SVG/cross-square.svg?component";
import IwyIconCrossSquareSolidSvg from "@ikkowy/icons/solid/SVG/cross-square.svg?component";
import IwyIconDarkRegularSvg from "@ikkowy/icons/regular/SVG/dark.svg?component";
import IwyIconDarkSolidSvg from "@ikkowy/icons/solid/SVG/dark.svg?component";
import IwyIconExitRegularSvg from "@ikkowy/icons/regular/SVG/exit.svg?component";
import IwyIconExitSolidSvg from "@ikkowy/icons/solid/SVG/exit.svg?component";
import IwyIconEyeRegularSvg from "@ikkowy/icons/regular/SVG/eye.svg?component";
import IwyIconEyeSolidSvg from "@ikkowy/icons/solid/SVG/eye.svg?component";
import IwyIconEyeOffRegularSvg from "@ikkowy/icons/regular/SVG/eye-off.svg?component";
import IwyIconEyeOffSolidSvg from "@ikkowy/icons/solid/SVG/eye-off.svg?component";
import IwyIconForeRegularSvg from "@ikkowy/icons/regular/SVG/fore.svg?component";
import IwyIconGearRegularSvg from "@ikkowy/icons/regular/SVG/gear.svg?component";
import IwyIconGearSolidSvg from "@ikkowy/icons/solid/SVG/gear.svg?component";
import IwyIconGroupRegularSvg from "@ikkowy/icons/regular/SVG/group.svg?component";
import IwyIconGroupSolidSvg from "@ikkowy/icons/solid/SVG/group.svg?component";
import IwyIconHelpRegularSvg from "@ikkowy/icons/regular/SVG/help.svg?component";
import IwyIconHelpSolidSvg from "@ikkowy/icons/solid/SVG/help.svg?component";
import IwyIconInfoRegularSvg from "@ikkowy/icons/regular/SVG/info.svg?component";
import IwyIconInfoSolidSvg from "@ikkowy/icons/solid/SVG/info.svg?component";
import IwyIconKeyRegularSvg from "@ikkowy/icons/regular/SVG/key.svg?component";
import IwyIconKeySolidSvg from "@ikkowy/icons/solid/SVG/key.svg?component";
import IwyIconLightRegularSvg from "@ikkowy/icons/regular/SVG/light.svg?component";
import IwyIconLightSolidSvg from "@ikkowy/icons/solid/SVG/light.svg?component";
import IwyIconMailRegularSvg from "@ikkowy/icons/regular/SVG/mail.svg?component";
import IwyIconMailSolidSvg from "@ikkowy/icons/solid/SVG/mail.svg?component";
import IwyIconMenuRegularSvg from "@ikkowy/icons/regular/SVG/menu.svg?component";
import IwyIconMenuOpenRegularSvg from "@ikkowy/icons/regular/SVG/menu-open.svg?component";
import IwyIconMessageRegularSvg from "@ikkowy/icons/regular/SVG/message.svg?component";
import IwyIconMessageSolidSvg from "@ikkowy/icons/solid/SVG/message.svg?component";
import IwyIconMessageOffRegularSvg from "@ikkowy/icons/regular/SVG/message-off.svg?component";
import IwyIconMessageOffSolidSvg from "@ikkowy/icons/solid/SVG/message-off.svg?component";
import IwyIconPencilRegularSvg from "@ikkowy/icons/regular/SVG/pencil.svg?component";
import IwyIconPhoneRegularSvg from "@ikkowy/icons/regular/SVG/phone.svg?component";
import IwyIconPhoneSolidSvg from "@ikkowy/icons/solid/SVG/phone.svg?component";
import IwyIconPhoneReceiverRegularSvg from "@ikkowy/icons/regular/SVG/phone-receiver.svg?component";
import IwyIconPhoneReceiverOffRegularSvg from "@ikkowy/icons/regular/SVG/phone-receiver-off.svg?component";
import IwyIconPinRegularSvg from "@ikkowy/icons/regular/SVG/pin.svg?component";
import IwyIconPinSolidSvg from "@ikkowy/icons/solid/SVG/pin.svg?component";
import IwyIconPinOffRegularSvg from "@ikkowy/icons/regular/SVG/pin-off.svg?component";
import IwyIconPinOffSolidSvg from "@ikkowy/icons/solid/SVG/pin-off.svg?component";
import IwyIconSearchRegularSvg from "@ikkowy/icons/regular/SVG/search.svg?component";
import IwyIconServerRegularSvg from "@ikkowy/icons/regular/SVG/server.svg?component";
import IwyIconServerSolidSvg from "@ikkowy/icons/solid/SVG/server.svg?component";
import IwyIconSquareRegularSvg from "@ikkowy/icons/regular/SVG/square.svg?component";
import IwyIconSquareSolidSvg from "@ikkowy/icons/solid/SVG/square.svg?component";
import IwyIconTaskRegularSvg from "@ikkowy/icons/regular/SVG/task.svg?component";
import IwyIconTaskSolidSvg from "@ikkowy/icons/solid/SVG/task.svg?component";
import IwyIconUnknownRegularSvg from "@ikkowy/icons/regular/SVG/unknown.svg?component";
import IwyIconUnknownSolidSvg from "@ikkowy/icons/solid/SVG/unknown.svg?component";
import IwyIconUserCircleRegularSvg from "@ikkowy/icons/regular/SVG/user-circle.svg?component";
import IwyIconUserCircleSolidSvg from "@ikkowy/icons/solid/SVG/user-circle.svg?component";
import IwyIconUserRegularSvg from "@ikkowy/icons/regular/SVG/user.svg?component";
import IwyIconUserSolidSvg from "@ikkowy/icons/solid/SVG/user.svg?component";
import IwyIconVaultRegularSvg from "@ikkowy/icons/regular/SVG/vault.svg?component";
import IwyIconVaultSolidSvg from "@ikkowy/icons/solid/SVG/vault.svg?component";

export default {
  install: (app, options) => {
    app.component("IwyIcon", IwyIcon);

    app.component("IwyIconArrowDownRegularSvg", IwyIconArrowDownRegularSvg);
    app.component("IwyIconArrowLeftRegularSvg", IwyIconArrowLeftRegularSvg);
    app.component("IwyIconArrowRightRegularSvg", IwyIconArrowRightRegularSvg);
    app.component("IwyIconArrowUpRegularSvg", IwyIconArrowUpRegularSvg);
    app.component("IwyIconBackRegularSvg", IwyIconBackRegularSvg);
    app.component("IwyIconBellRegularSvg", IwyIconBellRegularSvg);
    app.component("IwyIconBellSolidSvg", IwyIconBellSolidSvg);
    app.component("IwyIconBellOffRegularSvg", IwyIconBellOffRegularSvg);
    app.component("IwyIconBellOffSolidSvg", IwyIconBellOffSolidSvg);
    app.component("IwyIconBellRingRegularSvg", IwyIconBellRingRegularSvg);
    app.component("IwyIconBellRingSolidSvg", IwyIconBellRingSolidSvg);
    app.component("IwyIconBookRegularSvg", IwyIconBookRegularSvg);
    app.component("IwyIconBookSolidSvg", IwyIconBookSolidSvg);
    app.component("IwyIconBulletCircleRegularSvg", IwyIconBulletCircleRegularSvg);
    app.component("IwyIconBulletCircleSolidSvg", IwyIconBulletCircleSolidSvg);
    app.component("IwyIconBulletSquareRegularSvg", IwyIconBulletSquareRegularSvg);
    app.component("IwyIconBulletSquareSolidSvg", IwyIconBulletSquareSolidSvg);
    app.component("IwyIconCheckRegularSvg", IwyIconCheckRegularSvg);
    app.component("IwyIconCheckCircleRegularSvg", IwyIconCheckCircleRegularSvg);
    app.component("IwyIconCheckCircleSolidSvg", IwyIconCheckCircleSolidSvg);
    app.component("IwyIconCheckSquareRegularSvg", IwyIconCheckSquareRegularSvg);
    app.component("IwyIconCheckSquareSolidSvg", IwyIconCheckSquareSolidSvg);
    app.component("IwyIconCircleRegularSvg", IwyIconCircleRegularSvg);
    app.component("IwyIconCircleSolidSvg", IwyIconCircleSolidSvg);
    app.component("IwyIconClockRegularSvg", IwyIconClockRegularSvg);
    app.component("IwyIconClockSolidSvg", IwyIconClockSolidSvg);
    app.component("IwyIconCrossRegularSvg", IwyIconCrossRegularSvg);
    app.component("IwyIconCrossCircleRegularSvg", IwyIconCrossCircleRegularSvg);
    app.component("IwyIconCrossCircleSolidSvg", IwyIconCrossCircleSolidSvg);
    app.component("IwyIconCrossSquareRegularSvg", IwyIconCrossSquareRegularSvg);
    app.component("IwyIconCrossSquareSolidSvg", IwyIconCrossSquareSolidSvg);
    app.component("IwyIconDarkRegularSvg", IwyIconDarkRegularSvg);
    app.component("IwyIconDarkSolidSvg", IwyIconDarkSolidSvg);
    app.component("IwyIconExitRegularSvg", IwyIconExitRegularSvg);
    app.component("IwyIconExitSolidSvg", IwyIconExitSolidSvg);
    app.component("IwyIconEyeRegularSvg", IwyIconEyeRegularSvg);
    app.component("IwyIconEyeSolidSvg", IwyIconEyeSolidSvg);
    app.component("IwyIconEyeOffRegularSvg", IwyIconEyeOffRegularSvg);
    app.component("IwyIconEyeOffSolidSvg", IwyIconEyeOffSolidSvg);
    app.component("IwyIconForeRegularSvg", IwyIconForeRegularSvg);
    app.component("IwyIconGearRegularSvg", IwyIconGearRegularSvg);
    app.component("IwyIconGearSolidSvg", IwyIconGearSolidSvg);
    app.component("IwyIconGroupRegularSvg", IwyIconGroupRegularSvg);
    app.component("IwyIconGroupSolidSvg", IwyIconGroupSolidSvg);
    app.component("IwyIconHelpRegularSvg", IwyIconHelpRegularSvg);
    app.component("IwyIconHelpSolidSvg", IwyIconHelpSolidSvg);
    app.component("IwyIconInfoRegularSvg", IwyIconInfoRegularSvg);
    app.component("IwyIconInfoSolidSvg", IwyIconInfoSolidSvg);
    app.component("IwyIconKeyRegularSvg", IwyIconKeyRegularSvg);
    app.component("IwyIconKeySolidSvg", IwyIconKeySolidSvg);
    app.component("IwyIconLightRegularSvg", IwyIconLightRegularSvg);
    app.component("IwyIconLightSolidSvg", IwyIconLightSolidSvg);
    app.component("IwyIconMailRegularSvg", IwyIconMailRegularSvg);
    app.component("IwyIconMailSolidSvg", IwyIconMailSolidSvg);
    app.component("IwyIconMenuRegularSvg", IwyIconMenuRegularSvg);
    app.component("IwyIconMenuOpenRegularSvg", IwyIconMenuOpenRegularSvg);
    app.component("IwyIconMessageRegularSvg", IwyIconMessageRegularSvg);
    app.component("IwyIconMessageSolidSvg", IwyIconMessageSolidSvg);
    app.component("IwyIconMessageOffRegularSvg", IwyIconMessageOffRegularSvg);
    app.component("IwyIconMessageOffSolidSvg", IwyIconMessageOffSolidSvg);
    app.component("IwyIconPencilRegularSvg", IwyIconPencilRegularSvg);
    app.component("IwyIconPhoneRegularSvg", IwyIconPhoneRegularSvg);
    app.component("IwyIconPhoneSolidSvg", IwyIconPhoneSolidSvg);
    app.component("IwyIconPhoneReceiverRegularSvg", IwyIconPhoneReceiverRegularSvg);
    app.component("IwyIconPhoneReceiverOffRegularSvg", IwyIconPhoneReceiverOffRegularSvg);
    app.component("IwyIconPinRegularSvg", IwyIconPinRegularSvg);
    app.component("IwyIconPinSolidSvg", IwyIconPinSolidSvg);
    app.component("IwyIconPinOffRegularSvg", IwyIconPinOffRegularSvg);
    app.component("IwyIconPinOffSolidSvg", IwyIconPinOffSolidSvg);
    app.component("IwyIconSearchRegularSvg", IwyIconSearchRegularSvg);
    app.component("IwyIconServerRegularSvg", IwyIconServerRegularSvg);
    app.component("IwyIconServerSolidSvg", IwyIconServerSolidSvg);
    app.component("IwyIconSquareRegularSvg", IwyIconSquareRegularSvg);
    app.component("IwyIconSquareSolidSvg", IwyIconSquareSolidSvg);
    app.component("IwyIconTaskRegularSvg", IwyIconTaskRegularSvg);
    app.component("IwyIconTaskSolidSvg", IwyIconTaskSolidSvg);
    app.component("IwyIconUnknownRegularSvg", IwyIconUnknownRegularSvg);
    app.component("IwyIconUnknownSolidSvg", IwyIconUnknownSolidSvg);
    app.component("IwyIconUserCircleRegularSvg", IwyIconUserCircleRegularSvg);
    app.component("IwyIconUserCircleSolidSvg", IwyIconUserCircleSolidSvg);
    app.component("IwyIconUserRegularSvg", IwyIconUserRegularSvg);
    app.component("IwyIconUserSolidSvg", IwyIconUserSolidSvg);
    app.component("IwyIconVaultRegularSvg", IwyIconVaultRegularSvg);
    app.component("IwyIconVaultSolidSvg", IwyIconVaultSolidSvg);
  },
};

export { IconIndex };
